name: Deploy Backend to Hugging Face

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Push backend to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

          cd backend

          git init
          git branch -M main

          git lfs install
          git add .
          git commit -m "Auto deploy from GitHub" || true

          git remote add origin https://oauth2:${HF_TOKEN}@huggingface.co/spaces/Hanish23/agrigptnew

          git push --force origin main